name: 'fetch-file-action'
description: 'Fetch a file from a URL and save it to the filesystem'
author: 'FoxtrotPerry'

branding:
  icon: 'file-plus'
  color: 'blue'

inputs:
  url:
    description: 'URL to fetch the file from'
    required: true
  filename:
    description: 'Name of the file to save'
    required: true
  path:
    description: 'Path to save the file to'
    required: false
    default: './'

outputs:
  success:
    description: 'If the file was downloaded successfully'

runs:
  using: node20
  main: dist/index.js
